// packages/demo/src/vue/ColumnMenu.vue
<script setup lang="ts">
import Button from '@/components/ui/button/Button.vue'
import Checkbox from '@/components/ui/checkbox/Checkbox.vue'
import Popover from '@/components/ui/popover/Popover.vue'
import PopoverContent from '@/components/ui/popover/PopoverContent.vue'
import PopoverTrigger from '@/components/ui/popover/PopoverTrigger.vue'
import type { Column } from '@/components/ui/table/Table.vue'
import type { Run } from '../runs'

const props = defineProps<{
  columns: readonly Column<Run>[]
  hidden: ReadonlySet<string>
}>()

const emit = defineEmits<{ toggle: [key: string] }>()
</script>

<template>
  <Popover :positioning="{ placement: 'bottom-end' }">
    <PopoverTrigger as-child>
      <Button>
        <span class="inline-flex items-baseline gap-1.5">
          <span>Columns</span>
          <span v-if="props.hidden.size > 0" class="tnum font-data text-indigo">{{ props.hidden.size }}</span>
        </span>
      </Button>
    </PopoverTrigger>
    <PopoverContent>
      <ul>
        <li v-for="column in props.columns" :key="column.key">
          <Checkbox
            :checked="!props.hidden.has(column.key)"
            class="w-full px-(--cell-x) py-1 text-weft-dim transition-colors duration-(--dur-instant) ease-(--ease-beat) hover:bg-shed hover:text-weft"
            @update:checked="emit('toggle', column.key)"
          >
            {{ column.label }}
          </Checkbox>
        </li>
      </ul>
    </PopoverContent>
  </Popover>
</template>

// packages/demo/src/ColumnMenu.tsx
import { Button } from '@/components/ui/button/Button'
import { Checkbox } from '@/components/ui/checkbox/Checkbox'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover/Popover'
import type { Column } from '@/components/ui/table/Table'
import type { Run } from './runs'

interface ColumnMenuProps {
  readonly columns: readonly Column<Run>[]
  readonly hidden: ReadonlySet<string>
  readonly onToggle: (key: string) => void
}

export const ColumnMenu = ({ columns, hidden, onToggle }: ColumnMenuProps) => (
  <Popover positioning={{ placement: 'bottom-end' }}>
    <PopoverTrigger asChild>
      <Button>
        <span className="inline-flex items-baseline gap-1.5">
          <span>Columns</span>
          {hidden.size > 0 && <span className="tnum font-data text-indigo">{hidden.size}</span>}
        </span>
      </Button>
    </PopoverTrigger>
    <PopoverContent>
      <ul>
        {columns.map((column) => (
          <li key={column.key}>
            <Checkbox
              checked={!hidden.has(column.key)}
              onCheckedChange={() => onToggle(column.key)}
              className="w-full px-(--cell-x) py-1 text-weft-dim transition-colors duration-(--dur-instant) ease-(--ease-beat) hover:bg-shed hover:text-weft"
            >
              {column.label}
            </Checkbox>
          </li>
        ))}
      </ul>
    </PopoverContent>
  </Popover>
)
