// examples/starter-vue/src/components/ui/filter-bar/FilterBar.vue
<script lang="ts">
export interface FilterGroup {
  readonly key: string
  readonly label: string
  readonly options: readonly string[]
}

export type FilterValues = Readonly<Record<string, readonly string[]>>
</script>

<script setup lang="ts">
import { createListCollection } from '@ark-ui/vue/select'
import { computed, type HTMLAttributes } from 'vue'
import CloseIcon from '@/components/ui/icons/CloseIcon.vue'
import SearchIcon from '@/components/ui/icons/SearchIcon.vue'
import Select from '@/components/ui/select/Select.vue'
import SelectContent from '@/components/ui/select/SelectContent.vue'
import SelectOption from '@/components/ui/select/SelectOption.vue'
import SelectTrigger from '@/components/ui/select/SelectTrigger.vue'
import { cx } from '@/lib/cx'

const props = withDefaults(
  defineProps<{
    groups: readonly FilterGroup[]
    searchLabel?: string
    placeholder?: string
    class?: HTMLAttributes['class']
  }>(),
  { searchLabel: 'Search', placeholder: 'Search' },
)

const query = defineModel<string>('query', { required: true })
const values = defineModel<FilterValues>('values', { required: true })

const collections = computed(() =>
  props.groups.map((group) => ({
    group,
    collection: createListCollection({ items: group.options.map((value) => ({ label: value, value })) }),
  })),
)

const chips = computed(() =>
  props.groups.flatMap((group) => (values.value[group.key] ?? []).map((value) => ({ group, value }))),
)

const selectedIn = (key: string) => values.value[key] ?? []

const setGroup = (key: string, next: readonly string[]) => {
  values.value = { ...values.value, [key]: next }
}

const removeChip = (key: string, value: string) => {
  setGroup(
    key,
    selectedIn(key).filter((entry) => entry !== value),
  )
}
</script>

<template>
  <!-- vue does not know the `search` element yet, and a dynamic tag reaches it without a warning -->
  <component :is="'search'" :class="cx('flex flex-col gap-(--stack)', props.class)">
    <div class="flex flex-wrap items-center gap-(--stack)">
      <div class="ctl focus-ring h-(--ctl-h) min-w-55 flex-1">
        <SearchIcon class="size-3.5 text-weft-faint" />
        <input
          v-model="query"
          type="search"
          name="search"
          :placeholder="props.placeholder"
          :aria-label="props.searchLabel"
          class="w-full bg-transparent py-0 placeholder:text-weft-faint focus:outline-none"
        />
      </div>

      <Select
        v-for="entry in collections"
        :key="entry.group.key"
        :collection="entry.collection"
        multiple
        :model-value="[...selectedIn(entry.group.key)]"
        @update:model-value="(next: string[] | undefined) => setGroup(entry.group.key, next ?? [])"
      >
        <SelectTrigger>
          <span class="inline-flex items-baseline gap-1.5">
            <span :class="selectedIn(entry.group.key).length > 0 ? 'text-weft' : 'text-weft-dim'">
              {{ entry.group.label }}
            </span>
            <span v-if="selectedIn(entry.group.key).length > 0" class="tnum font-data text-indigo">
              {{ selectedIn(entry.group.key).length }}
            </span>
          </span>
        </SelectTrigger>
        <SelectContent>
          <SelectOption v-for="item in entry.collection.items" :key="item.value" :item="item" />
        </SelectContent>
      </Select>
    </div>

    <ul v-if="chips.length > 0" class="flex flex-wrap items-center gap-(--stack)">
      <li v-for="chip in chips" :key="`${chip.group.key}:${chip.value}`">
        <button
          type="button"
          class="inline-flex h-(--ctl-h) cursor-pointer items-center gap-1.5 border border-indigo/40 bg-indigo-wash px-(--cell-x) text-weft transition-colors duration-(--dur-instant) ease-(--ease-beat) hover:border-indigo"
          @click="removeChip(chip.group.key, chip.value)"
        >
          <span class="inline-flex items-baseline gap-1.5">
            <span class="font-data text-weft-dim">{{ chip.group.label.toLowerCase() }}</span>
            <span>{{ chip.value }}</span>
          </span>
          <CloseIcon class="size-3 text-weft-faint" />
        </button>
      </li>
      <li>
        <button
          type="button"
          class="h-(--ctl-h) cursor-pointer px-(--cell-x) text-weft-dim underline-offset-4 hover:text-weft hover:underline"
          @click="values = {}"
        >
          Clear filters
        </button>
      </li>
    </ul>
  </component>
</template>

// apps/lab/src/components/FilterBar.tsx
import { Portal } from '@ark-ui/react/portal'
import { Select, createListCollection } from '@ark-ui/react/select'
import { useMemo } from 'react'
import { CheckIcon, ChevronIcon, CloseIcon, SearchIcon } from './icons'

export interface Filters {
  readonly query: string
  readonly assays: readonly string[]
  readonly statuses: readonly string[]
  readonly owners: readonly string[]
}

export const EMPTY_FILTERS: Filters = { query: '', assays: [], statuses: [], owners: [] }

const CONTROL =
  'inline-flex items-center gap-1.5 border border-reed bg-ground px-(--cell-x) text-weft transition-colors duration-(--dur-instant) ease-(--ease-beat) hover:border-reed-lit'

interface FilterSelectProps {
  readonly label: string
  readonly options: readonly string[]
  readonly selected: readonly string[]
  readonly onSelect: (next: string[]) => void
}

const FilterSelect = ({ label, options, selected, onSelect }: FilterSelectProps) => {
  const collection = useMemo(
    () => createListCollection({ items: options.map((value) => ({ label: value, value })) }),
    [options],
  )

  return (
    <Select.Root
      collection={collection}
      multiple
      value={[...selected]}
      onValueChange={(details) => onSelect(details.value)}
    >
      <Select.Control>
        <Select.Trigger className={`${CONTROL} h-(--ctl-h) cursor-pointer`}>
          <span className="inline-flex items-baseline gap-1.5">
            <span className={selected.length > 0 ? 'text-weft' : 'text-weft-dim'}>{label}</span>
            {selected.length > 0 && <span className="tnum font-data text-indigo">{selected.length}</span>}
          </span>
          <ChevronIcon className="size-3 text-weft-faint" />
        </Select.Trigger>
      </Select.Control>
      <Portal>
        <Select.Positioner>
          <Select.Content className="min-w-42 border border-reed-lit bg-raised py-1 shadow-lg shadow-black/30 focus:outline-none">
            {collection.items.map((item) => (
              <Select.Item
                key={item.value}
                item={item}
                className="flex cursor-pointer items-center justify-between gap-3 px-(--cell-x) py-1 text-weft-dim data-highlighted:bg-indigo-wash data-highlighted:text-weft"
              >
                <Select.ItemText>{item.label}</Select.ItemText>
                <Select.ItemIndicator>
                  <CheckIcon className="size-3 text-indigo" />
                </Select.ItemIndicator>
              </Select.Item>
            ))}
          </Select.Content>
        </Select.Positioner>
      </Portal>
    </Select.Root>
  )
}

interface Chip {
  readonly group: keyof Omit<Filters, 'query'>
  readonly value: string
}

const GROUP_LABEL: Record<Chip['group'], string> = {
  assays: 'assay',
  statuses: 'status',
  owners: 'owner',
}

interface FilterBarProps {
  readonly filters: Filters
  readonly onChange: (next: Filters) => void
  readonly assays: readonly string[]
  readonly statuses: readonly string[]
  readonly owners: readonly string[]
}

export const FilterBar = ({ filters, onChange, assays, statuses, owners }: FilterBarProps) => {
  const chips: readonly Chip[] = [
    ...filters.assays.map((value) => ({ group: 'assays' as const, value })),
    ...filters.statuses.map((value) => ({ group: 'statuses' as const, value })),
    ...filters.owners.map((value) => ({ group: 'owners' as const, value })),
  ]

  const removeChip = (chip: Chip) => {
    onChange({ ...filters, [chip.group]: filters[chip.group].filter((value) => value !== chip.value) })
  }

  return (
    <search className="flex flex-col gap-(--stack)">
      <div className="flex flex-wrap items-center gap-(--stack)">
        <div className={`${CONTROL} focus-ring h-(--ctl-h) min-w-55 flex-1`}>
          <SearchIcon className="size-3.5 text-weft-faint" />
          <input
            type="search"
            name="run-search"
            value={filters.query}
            onChange={(event) => onChange({ ...filters, query: event.target.value })}
            placeholder="Search runs, samples, owners"
            aria-label="Search runs"
            className="w-full bg-transparent py-0 placeholder:text-weft-faint focus:outline-none"
          />
        </div>

        <FilterSelect
          label="Assay"
          options={assays}
          selected={filters.assays}
          onSelect={(next) => onChange({ ...filters, assays: next })}
        />
        <FilterSelect
          label="Status"
          options={statuses}
          selected={filters.statuses}
          onSelect={(next) => onChange({ ...filters, statuses: next })}
        />
        <FilterSelect
          label="Owner"
          options={owners}
          selected={filters.owners}
          onSelect={(next) => onChange({ ...filters, owners: next })}
        />
      </div>

      {chips.length > 0 && (
        <ul className="flex flex-wrap items-center gap-(--stack)">
          {chips.map((chip) => (
            <li key={`${chip.group}:${chip.value}`}>
              <button
                type="button"
                onClick={() => removeChip(chip)}
                className="inline-flex h-(--ctl-h) cursor-pointer items-center gap-1.5 border border-indigo/40 bg-indigo-wash px-(--cell-x) text-weft transition-colors duration-(--dur-instant) ease-(--ease-beat) hover:border-indigo"
              >
                <span className="inline-flex items-baseline gap-1.5">
                  <span className="font-data text-weft-dim">{GROUP_LABEL[chip.group]}</span>
                  {chip.value}
                </span>
                <CloseIcon className="size-3 text-weft-faint" />
              </button>
            </li>
          ))}
          <li>
            <button
              type="button"
              onClick={() => onChange({ ...EMPTY_FILTERS, query: filters.query })}
              className="h-(--ctl-h) cursor-pointer px-(--cell-x) text-weft-dim underline-offset-4 hover:text-weft hover:underline"
            >
              Clear filters
            </button>
          </li>
        </ul>
      )}
    </search>
  )
}
