// apps/lab/src/App.tsx
import { startTransition, useCallback, useEffect, useMemo, useState } from 'react'
import { flushSync } from 'react-dom'
import { Button } from '@/components/ui/button/Button'
import { CommandPalette, type Command } from '@/components/ui/command-palette/CommandPalette'
import { FilterBar, type FilterValues } from '@/components/ui/filter-bar/FilterBar'
import { Table } from '@/components/ui/table/Table'
import { Toaster } from '@/components/ui/toast/Toast'
import { CancelDialog } from '@demo/CancelDialog'
import { ColumnMenu } from '@demo/ColumnMenu'
import { QualityChart } from '@demo/QualityChart'
import { RunPanel } from '@demo/RunPanel'
import { runColumns } from '@demo/columns'
import { RUN_GROUPS, matchesFilters } from '@demo/filters'
import { longRuns, runs, type Run } from '@demo/runs'
import { toaster } from '@demo/toaster'

const DENSITIES = ['comfortable', 'compact', 'dense'] as const
type Density = (typeof DENSITIES)[number]

const THEMES = ['dark', 'light'] as const
type Theme = (typeof THEMES)[number]

const KNOBS = ['--row-h', '--cell-x', '--ui-text', '--ctl-h', '--stack', '--reed-pitch'] as const

const LONG_ROWS = 1000
const LOAD_MS = 450

interface Knob {
  readonly name: string
  readonly value: string
}

interface SegmentedProps<T extends string> {
  readonly legend: string
  readonly options: readonly T[]
  readonly value: T
  readonly onSelect: (next: T) => void
}

const LoomMark = () => (
  <svg
    className="size-7 shrink-0 -translate-y-[0.75px] text-indigo"
    viewBox="0 0 32 32"
    fill="none"
    aria-hidden="true"
    focusable="false"
  >
    <g stroke="currentColor" strokeWidth="2.4" strokeLinecap="round">
      <line x1="5" y1="4" x2="5" y2="28" />
      <line x1="12" y1="4" x2="12" y2="28" />
      <line x1="19" y1="4" x2="19" y2="28" />
      <line x1="26" y1="4" x2="26" y2="28" />
      <line x1="3" y1="21.5" x2="29" y2="21.5" />
    </g>
  </svg>
)

const Segmented = <T extends string>({ legend, options, value, onSelect }: SegmentedProps<T>) => (
  <fieldset className="flex items-center border border-reed">
    <legend className="sr-only">{legend}</legend>
    {options.map((option) => (
      <button
        key={option}
        type="button"
        aria-pressed={option === value}
        onClick={() => onSelect(option)}
        className="h-(--ctl-h) cursor-pointer px-(--cell-x) text-weft-dim transition-colors duration-(--dur-instant) ease-(--ease-beat) hover:text-weft aria-pressed:bg-indigo-wash aria-pressed:text-weft"
      >
        {option}
      </button>
    ))}
  </fieldset>
)

export const App = () => {
  const [density, setDensity] = useState<Density>('compact')
  const [theme, setTheme] = useState<Theme>('dark')
  const [query, setQuery] = useState('')
  const [values, setValues] = useState<FilterValues>({})
  const [paletteOpen, setPaletteOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [long, setLong] = useState(false)
  const [source, setSource] = useState<readonly Run[]>(runs)
  const [knobs, setKnobs] = useState<readonly Knob[]>([])
  const [detail, setDetail] = useState<Run | null>(null)
  const [pending, setPending] = useState<Run | null>(null)
  const [hidden, setHidden] = useState<ReadonlySet<string>>(new Set())
  const [selected, setSelected] = useState<ReadonlySet<string>>(new Set())

  /*
   * the cross fade needs the new palette inside its callback, so the state update
   * is flushed there. reduced motion sets the duration to 0ms and takes the plain
   * path, which spares the snapshot. a browser with no view transitions swaps.
   */
  const changeTheme = useCallback((next: Theme) => {
    const fade = Number.parseFloat(
      getComputedStyle(document.documentElement).getPropertyValue('--dur-overlay'),
    )
    if (fade === 0 || !document.startViewTransition) {
      setTheme(next)
      return
    }
    document.startViewTransition(() => {
      flushSync(() => setTheme(next))
    })
  }, [])

  useEffect(() => {
    const root = document.documentElement
    root.dataset.density = density
    root.dataset.theme = theme
    const style = getComputedStyle(root)
    setKnobs(KNOBS.map((token) => ({ name: token.slice(2), value: style.getPropertyValue(token).trim() })))
  }, [density, theme])

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key.toLowerCase() !== 'k') return
      if (!event.metaKey && !event.ctrlKey) return
      event.preventDefault()
      setPaletteOpen((open) => !open)
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [])

  /* the batch is built in memory, and the pause stands in for the fetch a real application makes */
  const toggleLong = useCallback(() => {
    const next = !long
    setLong(next)
    setLoading(true)
    window.setTimeout(() => {
      const batch = next ? longRuns(LONG_ROWS) : runs
      startTransition(() => {
        setSource(batch)
        setLoading(false)
      })
    }, LOAD_MS)
  }, [long])

  const visible = useMemo(() => source.filter((run) => matchesFilters(run, query, values)), [source, query, values])

  const exportable = useMemo(() => visible.filter((run) => selected.has(run.id)).length, [visible, selected])

  const allColumns = useMemo(() => runColumns(setDetail), [])
  const columns = useMemo(() => allColumns.filter((column) => !hidden.has(column.key)), [allColumns, hidden])

  const toggleColumn = (key: string) => {
    setHidden((current) => {
      const next = new Set(current)
      if (!next.delete(key)) next.add(key)
      return next
    })
  }

  const cancelRun = (run: Run) => {
    setPending(null)
    setDetail(null)
    toaster.create({
      title: `${run.id} is cancelled`,
      description: 'The instrument has stopped, and the reads stay on the run.',
      type: 'warning',
    })
  }

  const commands: readonly Command[] = useMemo(
    () => [
      ...DENSITIES.map((option) => ({
        id: `density-${option}`,
        group: 'Density',
        label: `Set density to ${option}`,
        run: () => setDensity(option),
      })),
      ...THEMES.map((option) => ({
        id: `theme-${option}`,
        group: 'Appearance',
        label: `Switch to ${option}`,
        run: () => changeTheme(option),
      })),
      {
        id: 'filter-running',
        group: 'Filters',
        label: 'Show running runs only',
        run: () => setValues({ status: ['running'] }),
      },
      {
        id: 'filter-failed',
        group: 'Filters',
        label: 'Show failed runs only',
        run: () => setValues({ status: ['failed'] }),
      },
      {
        id: 'filter-clear',
        group: 'Filters',
        label: 'Clear all filters',
        run: () => setValues({}),
      },
      {
        id: 'table-loading',
        group: 'Table',
        label: 'Toggle the loading state',
        run: () => setLoading((current) => !current),
      },
      {
        id: 'table-long',
        group: 'Table',
        label: `Toggle ${LONG_ROWS} rows`,
        run: () => toggleLong(),
      },
      {
        id: 'table-columns',
        group: 'Table',
        label: 'Show every column',
        run: () => setHidden(new Set()),
      },
      {
        id: 'run-open',
        group: 'Runs',
        label: 'Open the newest run',
        run: () => setDetail(runs[0]),
      },
    ],
    [toggleLong, changeTheme],
  )

  return (
    <div className="min-h-dvh px-6 py-8">
      <div className="mx-auto flex max-w-295 flex-col gap-6">
        <header className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <LoomMark />
              <div className="flex items-baseline gap-3">
                <p className="font-ui text-[34px] leading-none font-bold tracking-[-0.045em]">sley</p>
                <p className="font-data text-[19px] leading-none text-weft-dim">lab</p>
              </div>
            </div>
            <p className="mt-2.5 text-weft-dim">Components for interfaces that hold a lot of data.</p>
          </div>

          <div className="flex flex-wrap items-center gap-(--stack)">
            <ul className="tnum flex flex-wrap items-center gap-x-3 gap-y-1 font-data text-weft-faint">
              {knobs.map((knob) => (
                <li key={knob.name}>
                  {knob.name} <span className="text-weft-dim">{knob.value}</span>
                </li>
              ))}
            </ul>
            <Segmented legend="Density" options={DENSITIES} value={density} onSelect={setDensity} />
            <Segmented legend="Appearance" options={THEMES} value={theme} onSelect={changeTheme} />
            <Button onClick={() => setPaletteOpen(true)}>
              <span>Commands</span>
              <kbd className="font-data text-[11px] text-weft-faint">⌘K</kbd>
            </Button>
          </div>
        </header>

        <FilterBar
          query={query}
          onQueryChange={setQuery}
          groups={RUN_GROUPS}
          values={values}
          onValuesChange={setValues}
          searchLabel="Search runs"
          placeholder="Search runs, samples, owners"
        />

        <QualityChart />

        <Table
          rows={visible}
          columns={columns}
          rowId={(run) => run.id}
          title="Sequencing runs"
          noun={['run', 'runs']}
          emptyMessage="No run matches the filters."
          loading={loading}
          onSelectionChange={setSelected}
          actions={
            <>
              {exportable > 0 && (
                <Button
                  onClick={() =>
                    toaster.create({
                      title: `${exportable} ${exportable === 1 ? 'run is' : 'runs are'} queued for export`,
                      type: 'success',
                    })
                  }
                >
                  Export
                </Button>
              )}
              <ColumnMenu columns={allColumns} hidden={hidden} onToggle={toggleColumn} />
            </>
          }
        />
      </div>

      <RunPanel run={detail} onClose={() => setDetail(null)} onCancelRun={setPending} />
      <CancelDialog run={pending} onClose={() => setPending(null)} onConfirm={cancelRun} />
      <CommandPalette open={paletteOpen} onOpenChange={setPaletteOpen} commands={commands} />
      <Toaster toaster={toaster} />
    </div>
  )
}

// apps/lab-vue/src/App.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import Button from '@/components/ui/button/Button.vue'
import CommandPalette, { type Command } from '@/components/ui/command-palette/CommandPalette.vue'
import FilterBar from '@/components/ui/filter-bar/FilterBar.vue'
import Toaster from '@/components/ui/toast/Toaster.vue'
import CancelDialog from '@demo/vue/CancelDialog.vue'
import ColumnMenu from '@demo/vue/ColumnMenu.vue'
import QualityChart, { type DayRange } from '@demo/vue/QualityChart.vue'
import RunPanel from '@demo/vue/RunPanel.vue'
import RunTable from '@demo/vue/RunTable.vue'
import { LAB_COLUMNS } from '@demo/vue/columns'
import { toaster } from '@demo/vue/toaster'
import { RUN_GROUPS, matchesFilters, type FilterValues } from '@demo/filters'
import { withinRange } from '@demo/quality'
import { longRuns, runs, type Run } from '@demo/runs'
import LoomMark from './LoomMark.vue'
import Segmented from './Segmented.vue'

const DENSITIES = ['comfortable', 'compact', 'dense'] as const
type Density = (typeof DENSITIES)[number]

const THEMES = ['dark', 'light'] as const
type Theme = (typeof THEMES)[number]

const KNOBS = ['--row-h', '--cell-x', '--ui-text', '--ctl-h', '--stack', '--reed-pitch'] as const

const LONG_ROWS = 1000
const LOAD_MS = 450

const density = ref<Density>('compact')
const theme = ref<Theme>('dark')
const query = ref('')
const values = ref<FilterValues>({})
const paletteOpen = ref(false)
const loading = ref(false)
const long = ref(false)
const source = ref<readonly Run[]>(runs)
const knobs = ref<readonly { name: string; value: string }[]>([])
const detail = ref<Run | null>(null)
const pending = ref<Run | null>(null)
const hidden = ref<ReadonlySet<string>>(new Set())
const selected = ref<ReadonlySet<string>>(new Set())
const range = ref<DayRange | null>(null)

/*
 * the cross fade needs the new palette in the dom inside its callback, so the update is
 * flushed there. reduced motion sets the duration to 0ms and takes the plain path, which
 * spares the snapshot. a browser with no view transitions swaps.
 */
const changeTheme = (next: Theme) => {
  const fade = Number.parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--dur-overlay'))
  if (fade === 0 || !document.startViewTransition) {
    theme.value = next
    return
  }
  document.startViewTransition(() => {
    theme.value = next
    return nextTick()
  })
}

watch(
  [density, theme],
  () => {
    const root = document.documentElement
    root.dataset.density = density.value
    root.dataset.theme = theme.value
    const style = getComputedStyle(root)
    knobs.value = KNOBS.map((token) => ({ name: token.slice(2), value: style.getPropertyValue(token).trim() }))
  },
  { immediate: true },
)

const onKeyDown = (event: KeyboardEvent) => {
  if (event.key.toLowerCase() !== 'k') return
  if (!event.metaKey && !event.ctrlKey) return
  event.preventDefault()
  paletteOpen.value = !paletteOpen.value
}

onMounted(() => window.addEventListener('keydown', onKeyDown))
onUnmounted(() => window.removeEventListener('keydown', onKeyDown))

/* the batch is built in memory, and the pause stands in for the fetch a real application makes */
const toggleLong = () => {
  const next = !long.value
  long.value = next
  loading.value = true
  window.setTimeout(() => {
    source.value = next ? longRuns(LONG_ROWS) : runs
    loading.value = false
  }, LOAD_MS)
}

const visible = computed(() =>
  source.value.filter((run) => matchesFilters(run, query.value, values.value) && withinRange(run.started, range.value)),
)

const exportable = computed(() => visible.value.filter((run) => selected.value.has(run.id)).length)

const columns = computed(() => LAB_COLUMNS.filter((column) => !hidden.value.has(column.key)))

const toggleColumn = (key: string) => {
  const next = new Set(hidden.value)
  if (!next.delete(key)) next.add(key)
  hidden.value = next
}

const cancelRun = (run: Run) => {
  pending.value = null
  detail.value = null
  toaster.create({
    title: `${run.id} is cancelled`,
    description: 'The instrument has stopped, and the reads stay on the run.',
    type: 'warning',
  })
}

const exportRuns = () =>
  toaster.create({
    title: `${exportable.value} ${exportable.value === 1 ? 'run is' : 'runs are'} queued for export`,
    type: 'success',
  })

const commands = computed<readonly Command[]>(() => [
  ...DENSITIES.map((option) => ({
    id: `density-${option}`,
    group: 'Density',
    label: `Set density to ${option}`,
    run: () => {
      density.value = option
    },
  })),
  ...THEMES.map((option) => ({
    id: `theme-${option}`,
    group: 'Appearance',
    label: `Switch to ${option}`,
    run: () => changeTheme(option),
  })),
  {
    id: 'filter-running',
    group: 'Filters',
    label: 'Show running runs only',
    run: () => {
      values.value = { status: ['running'] }
    },
  },
  {
    id: 'filter-failed',
    group: 'Filters',
    label: 'Show failed runs only',
    run: () => {
      values.value = { status: ['failed'] }
    },
  },
  {
    id: 'filter-clear',
    group: 'Filters',
    label: 'Clear all filters',
    run: () => {
      values.value = {}
    },
  },
  {
    id: 'table-loading',
    group: 'Table',
    label: 'Toggle the loading state',
    run: () => {
      loading.value = !loading.value
    },
  },
  { id: 'table-long', group: 'Table', label: `Toggle ${LONG_ROWS} rows`, run: toggleLong },
  {
    id: 'table-columns',
    group: 'Table',
    label: 'Show every column',
    run: () => {
      hidden.value = new Set()
    },
  },
  {
    id: 'run-open',
    group: 'Runs',
    label: 'Open the newest run',
    run: () => {
      detail.value = runs[0]
    },
  },
])
</script>

<template>
  <div class="min-h-dvh px-6 py-8">
    <div class="mx-auto flex max-w-295 flex-col gap-6">
      <header class="flex flex-wrap items-end justify-between gap-4">
        <div>
          <div class="flex items-center gap-2">
            <LoomMark class="size-7 shrink-0 -translate-y-[0.75px] text-indigo" />
            <div class="flex items-baseline gap-3">
              <p class="font-ui text-[34px] leading-none font-bold tracking-[-0.045em]">sley</p>
              <p class="font-data text-[19px] leading-none text-weft-dim">lab</p>
            </div>
          </div>
          <p class="mt-2.5 text-weft-dim">Components for interfaces that hold a lot of data.</p>
        </div>

        <div class="flex flex-wrap items-center gap-(--stack)">
          <ul class="tnum flex flex-wrap items-center gap-x-3 gap-y-1 font-data text-weft-faint">
            <li v-for="knob in knobs" :key="knob.name">
              {{ knob.name }} <span class="text-weft-dim">{{ knob.value }}</span>
            </li>
          </ul>
          <Segmented legend="Density" :options="DENSITIES" :value="density" @select="density = $event" />
          <Segmented legend="Appearance" :options="THEMES" :value="theme" @select="changeTheme" />
          <Button @click="paletteOpen = true">
            <span>Commands</span>
            <kbd class="font-data text-[11px] text-weft-faint">⌘K</kbd>
          </Button>
        </div>
      </header>

      <FilterBar
        v-model:query="query"
        v-model:values="values"
        :groups="RUN_GROUPS"
        search-label="Search runs"
        placeholder="Search runs, samples, owners"
      />

      <QualityChart v-model:range="range" />

      <RunTable
        :rows="visible"
        :columns="columns"
        :loading="loading"
        @open="detail = $event"
        @selection-change="selected = $event"
      >
        <template #actions>
          <Button v-if="exportable > 0" @click="exportRuns">Export</Button>
          <ColumnMenu :columns="LAB_COLUMNS" :hidden="hidden" @toggle="toggleColumn" />
        </template>
      </RunTable>
    </div>

    <RunPanel :run="detail" @close="detail = null" @cancel-run="pending = $event" />
    <CancelDialog :run="pending" @close="pending = null" @confirm="cancelRun" />
    <CommandPalette v-model:open="paletteOpen" :commands="commands" />
    <Toaster :toaster="toaster" />
  </div>
</template>
