// packages/registry/src/components/ui/figure/Figure.vue
<script setup lang="ts">
import { computed, type HTMLAttributes } from 'vue'
import { cx } from '@/lib/cx'

const props = withDefaults(
  defineProps<{
    value: number
    digits?: number
    low?: boolean
    class?: HTMLAttributes['class']
  }>(),
  { digits: 1, low: false },
)

/* anything that is not a digit reads one step back */
const parts = computed(() => {
  const [whole, fraction] = props.value.toFixed(props.digits).split('.')
  return { whole, fraction }
})
</script>

<template>
  <span v-if="props.value === 0" :class="cx('reed-mark', props.class)" aria-hidden="true" />
  <span v-else :class="cx(props.low && 'reed-under', props.class)"
    >{{ parts.whole }}<span v-if="parts.fraction !== undefined" class="text-weft-faint">.{{ parts.fraction }}</span
    ><span v-if="props.low" class="sr-only"> below threshold</span></span
  >
</template>

// packages/registry/src/components/ui/figure/Figure.tsx
import { cx } from '@/lib/cx'

interface FigureProps {
  readonly value: number
  readonly digits?: number
  readonly low?: boolean
  readonly className?: string
}

/* anything that is not a digit reads one step back */
export const Figure = ({ value, digits = 1, low = false, className }: FigureProps) => {
  if (value === 0) return <span className={cx('reed-mark', className)} aria-hidden="true" />

  const [whole, fraction] = value.toFixed(digits).split('.')
  return (
    <span className={cx(low && 'reed-under', className)}>
      {whole}
      {fraction !== undefined && <span className="text-weft-faint">.{fraction}</span>}
      {low && <span className="sr-only"> below threshold</span>}
    </span>
  )
}

interface ElapsedProps {
  readonly minutes: number
  readonly className?: string
}

/* a head cannot hold two units, so a duration carries them in the cell */
export const Elapsed = ({ minutes, className }: ElapsedProps) => (
  <span className={className}>
    {Math.trunc(minutes / 60)}
    <span className="text-weft-faint">h </span>
    {String(minutes % 60).padStart(2, '0')}
    <span className="text-weft-faint">m</span>
  </span>
)
