// apps/lab-vue/src/Segmented.vue
<script setup lang="ts" generic="T extends string">
const props = defineProps<{
  legend: string
  options: readonly T[]
  value: T
}>()

const emit = defineEmits<{ select: [next: T] }>()
</script>

<template>
  <fieldset class="flex items-center border border-reed">
    <legend class="sr-only">{{ props.legend }}</legend>
    <button
      v-for="option in props.options"
      :key="option"
      type="button"
      :aria-pressed="option === props.value"
      class="h-(--ctl-h) cursor-pointer px-(--cell-x) text-weft-dim transition-colors duration-(--dur-instant) ease-(--ease-beat) hover:text-weft aria-pressed:bg-indigo-wash aria-pressed:text-weft"
      @click="emit('select', option)"
    >
      {{ option }}
    </button>
  </fieldset>
</template>

// apps/docs/src/site/Segmented.tsx
import { cx } from '@/lib/cx'

interface SegmentedProps<T extends string> {
  readonly legend: string
  readonly options: readonly T[]
  readonly value: T
  readonly onSelect: (next: T) => void
  readonly className?: string
}

export const Segmented = <T extends string>({
  legend,
  options,
  value,
  onSelect,
  className,
}: SegmentedProps<T>) => (
  <fieldset className={cx('flex items-center border border-reed', className)}>
    <legend className="sr-only">{legend}</legend>
    {options.map((option) => (
      <button
        key={option}
        type="button"
        aria-pressed={option === value}
        onClick={() => onSelect(option)}
        className="h-(--ctl-h) cursor-pointer px-(--cell-x) text-weft-dim transition-colors duration-(--dur-instant) ease-(--ease-beat) hover:text-weft aria-pressed:bg-indigo-wash aria-pressed:text-weft"
      >
        {option}
      </button>
    ))}
  </fieldset>
)
