// packages/registry/src/components/ui/empty-state/EmptyState.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cx } from '@/lib/cx'

const props = defineProps<{
  title: string
  description?: string
  class?: HTMLAttributes['class']
}>()
</script>

<!-- the text sits on a patch of cloth. no warp runs behind it. -->
<template>
  <div
    :class="
      cx('reed-warp flex flex-col items-center justify-center gap-(--stack) p-(--cell-x) text-center', props.class)
    "
    :style="{ minHeight: 'calc(var(--row-h) * 4)' }"
  >
    <div class="flex flex-col gap-1 bg-raised px-(--cell-x)">
      <p class="text-weft-dim">{{ props.title }}</p>
      <p v-if="props.description" class="text-weft-faint">{{ props.description }}</p>
    </div>
    <slot name="action" />
  </div>
</template>

// packages/registry/src/components/ui/empty-state/EmptyState.tsx
import type { ReactNode } from 'react'
import { cx } from '@/lib/cx'

interface EmptyStateProps {
  readonly title: string
  readonly description?: string
  readonly action?: ReactNode
  readonly className?: string
}

/* the text sits on a patch of cloth. no warp runs behind it. */
export const EmptyState = ({ title, description, action, className }: EmptyStateProps) => (
  <div
    className={cx('reed-warp flex flex-col items-center justify-center gap-(--stack) p-(--cell-x) text-center', className)}
    style={{ minHeight: 'calc(var(--row-h) * 4)' }}
  >
    <div className="flex flex-col gap-1 bg-raised px-(--cell-x)">
      <p className="text-weft-dim">{title}</p>
      {description && <p className="text-weft-faint">{description}</p>}
    </div>
    {action}
  </div>
)
