// packages/demo/src/vue/CancelDialog.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import Button from '@/components/ui/button/Button.vue'
import Dialog from '@/components/ui/dialog/Dialog.vue'
import DialogClose from '@/components/ui/dialog/DialogClose.vue'
import DialogContent from '@/components/ui/dialog/DialogContent.vue'
import DialogDescription from '@/components/ui/dialog/DialogDescription.vue'
import DialogFooter from '@/components/ui/dialog/DialogFooter.vue'
import DialogHeader from '@/components/ui/dialog/DialogHeader.vue'
import DialogTitle from '@/components/ui/dialog/DialogTitle.vue'
import type { Run } from '../runs'

const props = defineProps<{ run: Run | null }>()

const emit = defineEmits<{
  close: []
  confirm: [run: Run]
}>()

/* holds the run until the dialog has left the screen */
const shown = ref<Run | null>(props.run)

watch(
  () => props.run,
  (run) => {
    if (run !== null) shown.value = run
  },
)
</script>

<template>
  <Dialog
    v-if="shown"
    :open="props.run !== null"
    role="alertdialog"
    @update:open="
      (open: boolean) => {
        if (!open) emit('close')
      }
    "
  >
    <DialogContent>
      <DialogHeader>
        <DialogTitle>Cancel {{ shown.id }}?</DialogTitle>
        <DialogDescription>
          The instrument stops, and the reads it has written stay on the run.
        </DialogDescription>
      </DialogHeader>
      <DialogFooter>
        <DialogClose as-child>
          <Button variant="quiet">Keep the run</Button>
        </DialogClose>
        <Button variant="danger" @click="emit('confirm', shown)">Cancel the run</Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// apps/lab/src/runs/CancelDialog.tsx
import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button/Button'
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog/Dialog'
import type { Run } from '../data/runs'

interface CancelDialogProps {
  readonly run: Run | null
  readonly onClose: () => void
  readonly onConfirm: (run: Run) => void
}

export const CancelDialog = ({ run, onClose, onConfirm }: CancelDialogProps) => {
  /* holds the run until the dialog has left the screen */
  const [shown, setShown] = useState(run)

  useEffect(() => {
    if (run !== null) setShown(run)
  }, [run])

  if (shown === null) return null

  return (
    <Dialog
      open={run !== null}
      role="alertdialog"
      onOpenChange={(details) => {
        if (!details.open) onClose()
      }}
    >
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Cancel {shown.id}?</DialogTitle>
          <DialogDescription>
            The instrument stops, and the reads it has written stay on the run.
          </DialogDescription>
        </DialogHeader>
        <DialogFooter>
          <DialogClose asChild>
            <Button variant="quiet">Keep the run</Button>
          </DialogClose>
          <Button variant="danger" onClick={() => onConfirm(shown)}>
            Cancel the run
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
