// packages/demo/src/vue/RunPanel.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import Button from '@/components/ui/button/Button.vue'
import EmptyState from '@/components/ui/empty-state/EmptyState.vue'
import Field from '@/components/ui/field/Field.vue'
import FieldError from '@/components/ui/field/FieldError.vue'
import FieldHint from '@/components/ui/field/FieldHint.vue'
import FieldInput from '@/components/ui/field/FieldInput.vue'
import FieldLabel from '@/components/ui/field/FieldLabel.vue'
import FieldSet from '@/components/ui/field/FieldSet.vue'
import FieldTextarea from '@/components/ui/field/FieldTextarea.vue'
import Elapsed from '@/components/ui/figure/Elapsed.vue'
import Figure from '@/components/ui/figure/Figure.vue'
import Panel from '@/components/ui/panel/Panel.vue'
import Tabs from '@/components/ui/tabs/Tabs.vue'
import TabsList from '@/components/ui/tabs/TabsList.vue'
import TabsPanel from '@/components/ui/tabs/TabsPanel.vue'
import TabsTab from '@/components/ui/tabs/TabsTab.vue'
import { stamp } from '../format'
import type { Run } from '../runs'
import { STATUS_TONE } from '../status'
import { Q30_FLOOR } from './columns'
import { toaster } from './toaster'

const props = defineProps<{ run: Run | null }>()

const emit = defineEmits<{
  close: []
  cancelRun: [run: Run]
}>()

/* the panel needs its run while it slides out */
const shown = ref<Run | null>(props.run)
const owner = ref('')
const note = ref('')

watch(
  () => props.run,
  (run) => {
    if (run === null) return
    shown.value = run
    owner.value = run.owner
    note.value = ''
  },
  { immediate: true },
)

const cancellable = computed(() => shown.value?.status === 'running' || shown.value?.status === 'queued')

const DETAIL = 'flex items-baseline justify-between gap-4 border-b border-reed/60 py-1.5'

const watchRun = (run: Run) =>
  toaster.create({
    title: `Watching ${run.id}`,
    description: 'A toast follows the first read.',
    type: 'info',
  })

const reassign = (run: Run) => toaster.create({ title: `${run.id} goes to ${owner.value.trim()}`, type: 'success' })
</script>

<template>
  <Panel
    v-if="shown"
    :open="props.run !== null"
    :title="shown.id"
    :description="`${shown.assay} on ${shown.sample}`"
    @update:open="
      (open: boolean) => {
        if (!open) emit('close')
      }
    "
  >
    <!-- the key remounts the tabs and the form for another run -->
    <Tabs :key="shown.id" default-value="overview" class="flex flex-col">
      <TabsList class="px-(--cell-x)">
        <TabsTab value="overview">Overview</TabsTab>
        <TabsTab value="metrics">Metrics</TabsTab>
        <TabsTab value="notes">Notes</TabsTab>
      </TabsList>

      <TabsPanel value="overview" class="px-(--cell-x)">
        <dl class="flex flex-col">
          <div :class="DETAIL">
            <dt class="text-weft-dim">Sample</dt>
            <dd class="tnum font-data text-weft">{{ shown.sample }}</dd>
          </div>
          <div :class="DETAIL">
            <dt class="text-weft-dim">Assay</dt>
            <dd class="tnum font-data text-weft">{{ shown.assay }}</dd>
          </div>
          <div :class="DETAIL">
            <dt class="text-weft-dim">Status</dt>
            <dd :class="`tnum inline-flex items-center gap-1.5 ${STATUS_TONE[shown.status]}`">
              <span class="size-1.25 rounded-full bg-current" />
              <span class="font-data">{{ shown.status }}</span>
            </dd>
          </div>
          <div :class="DETAIL">
            <dt class="text-weft-dim">Started</dt>
            <dd class="tnum font-data text-weft">{{ stamp(shown.started).full }}</dd>
          </div>
          <div :class="DETAIL">
            <dt class="text-weft-dim">Elapsed</dt>
            <dd class="tnum font-data text-weft"><Elapsed :minutes="shown.duration" /></dd>
          </div>
          <!-- a person, not a machine value: no data face -->
          <div :class="DETAIL">
            <dt class="text-weft-dim">Owner</dt>
            <dd class="tnum text-weft">{{ shown.owner }}</dd>
          </div>
        </dl>
      </TabsPanel>

      <TabsPanel value="metrics" class="px-(--cell-x)">
        <EmptyState v-if="shown.reads === 0" title="No metrics yet" description="The run has produced no reads.">
          <template #action>
            <Button variant="quiet" @click="watchRun(shown)">Tell me when it starts</Button>
          </template>
        </EmptyState>

        <dl v-else class="flex flex-col">
          <div :class="DETAIL">
            <dt class="text-weft-dim">Reads (M)</dt>
            <dd class="tnum font-data text-weft"><Figure :value="shown.reads" /></dd>
          </div>
          <div :class="DETAIL">
            <dt class="text-weft-dim">Q30 (%)</dt>
            <dd class="tnum font-data text-weft"><Figure :value="shown.q30" :low="shown.q30 < Q30_FLOOR" /></dd>
          </div>
          <div :class="DETAIL">
            <dt class="text-weft-dim">Coverage (x)</dt>
            <dd class="tnum font-data text-weft"><Figure :value="shown.coverage" /></dd>
          </div>
        </dl>
      </TabsPanel>

      <TabsPanel value="notes" class="px-(--cell-x)">
        <FieldSet legend="Reassign the run">
          <Field required :invalid="owner.trim() === ''">
            <FieldLabel>New owner</FieldLabel>
            <FieldInput v-model="owner" />
            <FieldHint>The person who answers for the result.</FieldHint>
            <FieldError>Name the person who takes the run.</FieldError>
          </Field>

          <Field>
            <FieldLabel>Note</FieldLabel>
            <FieldTextarea v-model="note" />
            <FieldHint>The note goes on the run, and the current owner reads it.</FieldHint>
          </Field>

          <div class="flex justify-end">
            <Button variant="primary" :disabled="owner.trim() === ''" @click="reassign(shown)">Save</Button>
          </div>
        </FieldSet>
      </TabsPanel>
    </Tabs>

    <template #footer>
      <Button variant="quiet" @click="emit('close')">Close</Button>
      <Button :disabled="!cancellable" @click="emit('cancelRun', shown)">Cancel the run</Button>
    </template>
  </Panel>
</template>

// apps/lab/src/runs/RunPanel.tsx
import { useEffect, useState, type ReactNode } from 'react'
import { Button } from '@/components/ui/button/Button'
import { EmptyState } from '@/components/ui/empty-state/EmptyState'
import {
  Field,
  FieldError,
  FieldHint,
  FieldInput,
  FieldLabel,
  FieldSet,
  FieldTextarea,
} from '@/components/ui/field/Field'
import { Elapsed, Figure } from '@/components/ui/figure/Figure'
import { Panel } from '@/components/ui/panel/Panel'
import { Tabs, TabsList, TabsPanel, TabsTab } from '@/components/ui/tabs/Tabs'
import type { Run } from '../data/runs'
import { toaster } from '../toaster'
import { stamp } from './format'
import { STATUS_TONE } from './status'
import { Q30_FLOOR } from './columns'

interface DetailProps {
  readonly label: string
  readonly children: ReactNode
}

const Detail = ({ label, children }: DetailProps) => (
  <div className="flex items-baseline justify-between gap-4 border-b border-reed/60 py-1.5">
    <dt className="text-weft-dim">{label}</dt>
    <dd className="tnum text-weft">{children}</dd>
  </div>
)

const Overview = ({ run }: { readonly run: Run }) => (
  <dl className="flex flex-col">
    <Detail label="Sample">
      <span className="font-data">{run.sample}</span>
    </Detail>
    <Detail label="Assay">
      <span className="font-data">{run.assay}</span>
    </Detail>
    <Detail label="Status">
      <span className={`inline-flex items-center gap-1.5 ${STATUS_TONE[run.status]}`}>
        <span className="size-1.25 rounded-full bg-current" />
        <span className="font-data">{run.status}</span>
      </span>
    </Detail>
    <Detail label="Started">
      <span className="font-data">{stamp(run.started).full}</span>
    </Detail>
    <Detail label="Elapsed">
      <span className="font-data">
        <Elapsed minutes={run.duration} />
      </span>
    </Detail>
    {/* a person, not a machine value: no data face */}
    <Detail label="Owner">{run.owner}</Detail>
  </dl>
)

const Metrics = ({ run }: { readonly run: Run }) => {
  if (run.reads === 0) {
    return (
      <EmptyState
        title="No metrics yet"
        description="The run has produced no reads."
        action={
          <Button
            variant="quiet"
            onClick={() => toaster.create({ title: `Watching ${run.id}`, description: 'A toast follows the first read.', type: 'info' })}
          >
            Tell me when it starts
          </Button>
        }
      />
    )
  }

  return (
    <dl className="flex flex-col">
      <Detail label="Reads (M)">
        <span className="font-data">
          <Figure value={run.reads} />
        </span>
      </Detail>
      <Detail label="Q30 (%)">
        <span className="font-data">
          <Figure value={run.q30} low={run.q30 < Q30_FLOOR} />
        </span>
      </Detail>
      <Detail label="Coverage (x)">
        <span className="font-data">
          <Figure value={run.coverage} />
        </span>
      </Detail>
    </dl>
  )
}

const Reassign = ({ run }: { readonly run: Run }) => {
  const [owner, setOwner] = useState(run.owner)
  const [note, setNote] = useState('')

  return (
    <FieldSet legend="Reassign the run">
      <Field required invalid={owner.trim() === ''}>
        <FieldLabel>New owner</FieldLabel>
        <FieldInput value={owner} onChange={(event) => setOwner(event.target.value)} />
        <FieldHint>The person who answers for the result.</FieldHint>
        <FieldError>Name the person who takes the run.</FieldError>
      </Field>

      <Field>
        <FieldLabel>Note</FieldLabel>
        <FieldTextarea value={note} onChange={(event) => setNote(event.target.value)} />
        <FieldHint>The note goes on the run, and the current owner reads it.</FieldHint>
      </Field>

      <div className="flex justify-end">
        <Button
          variant="primary"
          disabled={owner.trim() === ''}
          onClick={() =>
            toaster.create({ title: `${run.id} goes to ${owner.trim()}`, type: 'success' })
          }
        >
          Save
        </Button>
      </div>
    </FieldSet>
  )
}

interface RunPanelProps {
  readonly run: Run | null
  readonly onClose: () => void
  readonly onCancelRun: (run: Run) => void
}

export const RunPanel = ({ run, onClose, onCancelRun }: RunPanelProps) => {
  /* the panel needs its run while it slides out */
  const [shown, setShown] = useState(run)

  useEffect(() => {
    if (run !== null) setShown(run)
  }, [run])

  if (shown === null) return null

  return (
    <Panel
      open={run !== null}
      onOpenChange={(open) => {
        if (!open) onClose()
      }}
      title={shown.id}
      description={`${shown.assay} on ${shown.sample}`}
      footer={
        <>
          <Button variant="quiet" onClick={onClose}>
            Close
          </Button>
          <Button
            disabled={shown.status !== 'running' && shown.status !== 'queued'}
            onClick={() => onCancelRun(shown)}
          >
            Cancel the run
          </Button>
        </>
      }
    >
      {/* the key remounts the tabs and the form for another run */}
      <Tabs key={shown.id} defaultValue="overview" className="flex flex-col">
        <TabsList className="px-(--cell-x)">
          <TabsTab value="overview">Overview</TabsTab>
          <TabsTab value="metrics">Metrics</TabsTab>
          <TabsTab value="notes">Notes</TabsTab>
        </TabsList>
        <TabsPanel value="overview" className="px-(--cell-x)">
          <Overview run={shown} />
        </TabsPanel>
        <TabsPanel value="metrics" className="px-(--cell-x)">
          <Metrics run={shown} />
        </TabsPanel>
        <TabsPanel value="notes" className="px-(--cell-x)">
          <Reassign run={shown} />
        </TabsPanel>
      </Tabs>
    </Panel>
  )
}
