// examples/starter/src/components/ui/checkbox/Checkbox.tsx
import { Checkbox as ArkCheckbox } from '@ark-ui/react/checkbox'
import type { ReactNode } from 'react'
import { CheckIcon } from '@/components/ui/icons/Icons'
import { cx } from '@/lib/cx'

export type CheckedState = boolean | 'indeterminate'

interface CheckboxProps {
  readonly checked: CheckedState
  readonly onCheckedChange: (checked: CheckedState) => void
  readonly children?: ReactNode
  /* names a box that shows no text */
  readonly label?: string
  readonly className?: string
}

const CONTROL =
  'grid size-(--ctl-box) shrink-0 place-items-center border border-reed-lit text-ground transition-colors duration-(--dur-instant) ease-(--ease-beat) data-[state=checked]:border-indigo data-[state=checked]:bg-indigo data-[state=indeterminate]:border-indigo data-[state=indeterminate]:bg-indigo'

/* the ark root is a label element, so the text inside it toggles the box */
export const Checkbox = ({ checked, onCheckedChange, children, label, className }: CheckboxProps) => (
  <ArkCheckbox.Root
    checked={checked}
    onCheckedChange={(details) => onCheckedChange(details.checked)}
    className={cx('ctl-align inline-flex cursor-pointer items-center gap-2', className)}
  >
    <ArkCheckbox.Control className={CONTROL}>
      <ArkCheckbox.Indicator>
        <CheckIcon className="size-2.75" />
      </ArkCheckbox.Indicator>
      <ArkCheckbox.Indicator indeterminate>
        <span className="block h-px w-1.75 bg-current" />
      </ArkCheckbox.Indicator>
    </ArkCheckbox.Control>
    {children !== undefined && <ArkCheckbox.Label>{children}</ArkCheckbox.Label>}
    <ArkCheckbox.HiddenInput aria-label={children === undefined ? label : undefined} />
  </ArkCheckbox.Root>
)

// examples/starter-vue/src/components/ui/checkbox/Checkbox.vue
<script lang="ts">
export type CheckedState = boolean | 'indeterminate'
</script>

<script setup lang="ts">
import { Checkbox as ArkCheckbox } from '@ark-ui/vue/checkbox'
import { useSlots, type HTMLAttributes } from 'vue'
import CheckIcon from '@/components/ui/icons/CheckIcon.vue'
import { cx } from '@/lib/cx'

const props = defineProps<{
  /* names a box that shows no text */
  label?: string
  class?: HTMLAttributes['class']
}>()

const checked = defineModel<CheckedState>('checked', { required: true })

const slots = useSlots()

const CONTROL =
  'grid size-(--ctl-box) shrink-0 place-items-center border border-reed-lit text-ground transition-colors duration-(--dur-instant) ease-(--ease-beat) data-[state=checked]:border-indigo data-[state=checked]:bg-indigo data-[state=indeterminate]:border-indigo data-[state=indeterminate]:bg-indigo'
</script>

<!-- the ark root is a label element, so the text inside it toggles the box -->
<template>
  <ArkCheckbox.Root
    v-model:checked="checked"
    :class="cx('ctl-align inline-flex cursor-pointer items-center gap-2', props.class)"
  >
    <ArkCheckbox.Control :class="CONTROL">
      <ArkCheckbox.Indicator>
        <CheckIcon class="size-2.75" />
      </ArkCheckbox.Indicator>
      <ArkCheckbox.Indicator indeterminate>
        <span class="block h-px w-1.75 bg-current" />
      </ArkCheckbox.Indicator>
    </ArkCheckbox.Control>
    <ArkCheckbox.Label v-if="slots.default">
      <slot />
    </ArkCheckbox.Label>
    <ArkCheckbox.HiddenInput :aria-label="slots.default ? undefined : props.label" />
  </ArkCheckbox.Root>
</template>
