// packages/registry/src/components/ui/tooltip/Tooltip.tsx
import { Tooltip as ArkTooltip } from '@ark-ui/react/tooltip'
import { Portal } from '@ark-ui/react/portal'
import type { ReactElement, ReactNode } from 'react'
import { cx } from '@/lib/cx'

interface TooltipProps {
  readonly content: ReactNode
  /* asChild: the trigger becomes this element */
  readonly children: ReactElement
  readonly openDelay?: number
  readonly closeDelay?: number
  readonly className?: string
}

/* faster than the ark default, for an interface with many small questions */
export const Tooltip = ({ content, children, openDelay = 200, closeDelay = 80, className }: TooltipProps) => (
  <ArkTooltip.Root openDelay={openDelay} closeDelay={closeDelay}>
    <ArkTooltip.Trigger asChild>{children}</ArkTooltip.Trigger>
    <Portal>
      <ArkTooltip.Positioner>
        <ArkTooltip.Content
          className={cx(
            'layer max-w-64 px-2 py-1 text-weft data-[state=open]:animate-[fade_var(--dur-instant)_var(--ease-beat)]',
            className,
          )}
        >
          {content}
        </ArkTooltip.Content>
      </ArkTooltip.Positioner>
    </Portal>
  </ArkTooltip.Root>
)

// packages/registry/src/components/ui/tooltip/Tooltip.vue
<script setup lang="ts">
import { Tooltip as ArkTooltip } from '@ark-ui/vue/tooltip'
import type { HTMLAttributes } from 'vue'
import { cx } from '@/lib/cx'

/* faster than the ark default, for an interface with many small questions */
const props = withDefaults(
  defineProps<{
    content?: string
    openDelay?: number
    closeDelay?: number
    class?: HTMLAttributes['class']
  }>(),
  { openDelay: 200, closeDelay: 80 },
)
</script>

<template>
  <ArkTooltip.Root :open-delay="props.openDelay" :close-delay="props.closeDelay">
    <!-- the trigger becomes whatever the caller put in the slot -->
    <ArkTooltip.Trigger as-child>
      <slot />
    </ArkTooltip.Trigger>
    <Teleport to="body">
      <ArkTooltip.Positioner>
        <ArkTooltip.Content
          :class="
            cx(
              'layer max-w-64 px-2 py-1 text-weft data-[state=open]:animate-[fade_var(--dur-instant)_var(--ease-beat)]',
              props.class,
            )
          "
        >
          <slot name="content">{{ props.content }}</slot>
        </ArkTooltip.Content>
      </ArkTooltip.Positioner>
    </Teleport>
  </ArkTooltip.Root>
</template>
